version: '3.8'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"  # LocalStack S3 endpoint
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
